### ISSUE TITLE
Does not show all payment methods in production mode

### ISSUE THREAD

**Issue by vipwire** [ICEPAYdev/WHMCS#1]
Hello,

Module version 1.2
WHMCS version 6.3.1

On the checkout step, icepay do not show all payment methods in production mode. Wire Transfer only available.
Please let me know how to solve it.
![icepay](https://cloud.githubusercontent.com/assets/25798764/22983732/b6a6f516-f3ab-11e6-9aea-fdd6e02c7cb4.PNG)
![payment page](https://cloud.githubusercontent.com/assets/25798764/22983733/b6ab3edc-f3ab-11e6-86e9-bc838b7e4d29.PNG)

Please check attached screenshots.

**Comment by Smashmint** [comment]
Hey, sorry the late reply.

Will try the reproduce the issue the next few days.

**Comment by vipwire** [comment]
Hello Sir/Madam,

We are closing Icepay account since of all these delays. You do not need this work for us. Do it for new Icepay customers.

Thank you.
